CREATE TABLE user (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) UNIQUE,
	real_name VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin,
	email VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin,
	hash VARCHAR(2047) CHARACTER SET utf8 COLLATE utf8_bin,
	salt VARCHAR(2047) CHARACTER SET utf8 COLLATE utf8_bin,
	admin BOOLEAN,
	disabled BOOLEAN NOT NULL
);

CREATE TABLE item (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin,
	description VARCHAR(1023) CHARACTER SET utf8 COLLATE utf8_bin,
	price INT NOT NULL,
	disabled BOOLEAN NOT NULL
);

CREATE TABLE transaction (
	user_id INT NOT NULL,
	value INT NOT NULL
);

CREATE TABLE purchase (
	user_id INT NOT NULL,
	item_id INT NOT NULL
);